POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Akshay A",
    "number": 12312
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": 12312
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}